### ISSUE TITLE
Endpoint not working!

### ISSUE THREAD

**Issue by hyaix** [deepnight-ai/aiforcause#4]
Hello, thank you for providing this endpoint!

3 days ago, the endpoint was still functional. However, it is currently not working. When accessing the endpoint in the browser, a JSON error message stating "method not allowed" used to appear. Now the page loads indefinitely. If the API is accessed correctly, the response continues loading indefinitely and eventually ends with a "bad request" error.

**Comment by deepnight-ai** [comment]
Greetings @hyaix,
Thanks for bringing this to our attention. We're looking into it and will get back to you ASAP!

Regards,
Team DEEPNIGHT

**Comment by deepnight-ai** [comment]
Hey @hyaix, apologies for the delayed response.
It seems like there was an issue in handling streaming.

The issue has now been fixed.


Thanks once again for bringing this to our attention.


Regards,
Team DEEPNIGHT
